import Head from 'next/head';
import { Drawer } from '../components/Drawer';
import { Header } from '../components/Header';
import { Introduce } from '../components/introduce/Introduce';
import { Innovation } from '../components/innovation/Innovation';
import { Features } from '../components/features/Features';
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <Header />
      <Drawer />

      <main>
        <Introduce />
        <Innovation />
        <Features />
      </main>
    </>
  );
}
